### ISSUE TITLE
/# flag not workiing

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#18]
The /# flag is used to tell the engine to ignore the next color/font flag in text added by the designer and in scripts in the databases
It is not functioning and currently is only displays "/#" in the text.

**Comment by grannypron** [comment]
Just to be sure I have this right, if I used the following text, 

word word /# word /t orange word /r red

then the sentence above would have one red word in it and no orange words in it?

Or would it have no red words and no orange words?

**Comment by grannypron** [comment]
"I honestly don't know. It was only ever used in lines with only one color flag for the default release.
Okay,, just looked at my test mod and I used it once per line in a Text Statement event, and there was only one color flag per line. That makes me think it counteracts the next color flag only."

**Comment by grannypron** [comment]
[DungeonCraftEditor_5.26_62dfc23.zip](https://github.com/grannypron/uaf/files/5675681/DungeonCraftEditor_5.26_62dfc23.zip)

Alpha build

**Comment by manikus** [comment]
Just a super quick test, but the /# flag worked in a Text Startement event. I still need to test it in teh classes database and the Special Abilities database.
