### ISSUE TITLE
credits images and music

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#19]
Via Global Settings, adding additional a is not working properly. Only the first file is displayed. The image and the music are present for approximately one second and then end. Additional images are not displayed at all.

**Comment by grannypron** [comment]
I think what happens here is that the credits screen goes away when the user clicks/presses a button.   If I am careful not to press a button after exiting, the credits screen stays up for me.  If we want to make the credits screen stay up regardless of input when it is displaying, we could do that.   Have to decide if that applies to the first credits screen or all I suppose.  Also have to decide if the "delay N seconds" feature overrides that or not.

Agree that multiple credits screens are not working.  I probably just never implemented it, even though I used the multiple screens selection window that was already there.

**Comment by manikus** [comment]
Have you tried credits with music playing? I do not touch anything and it is up for about one second.

**Comment by grannypron** [comment]
Ooops yes now it is doing what you are saying.  The first few times it didn't do that but now I see it yep.

**Comment by grannypron** [comment]
I can see what is going on here.  Got it to work with keypresses to advance multiple times, but still working on getting it to work with the "timeouts"

**Comment by grannypron** [comment]
[DungeonCraft_5.26_6653316.zip](https://github.com/grannypron/uaf/files/5667584/DungeonCraft_5.26_6653316.zip)

This includes uaf_00017 & uaf_00019 fixes.

**Comment by grannypron** [comment]
"I tried all the permutations I could think of - one image, multiple images, with sound, without sound, timed, and waiting for player's click. They all worked as expected. 8)
Good job, and thank you very much. :D :D :D"
