### ISSUE TITLE
Feature Request: item database baseclass use

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#37]
Currently in the items database, each baseclass that can use the item, it is it something like:
baseclass = fighter
baseclass = priest
baseclass = thief
etc...
One line for each baseclass.
What I would like is to have an option - baseclass = any - which means that all baseclasses can use it.
We do this in the baseclass database for Alignment (so see an exxample).

**Comment by grannypron** [comment]
At first glance, I think this would come down to ITEM_DATA::IsUsableByBaseclass() and hardcoding a check in there to just short circuit with a true if the BASECLASS_ID == "any".

**Comment by grannypron** [comment]
Reading the item from the inventory screen actually checks ITEM_DATA::IsUsableByClass().

Adding code to do the check is pretty straightforward, however, when I modify items.txt to have the baseclass = any line, it seems to fail loading somehow and GetBaseclassCount() for the item returns 0.   Will probably have to put in a check in the serialization and/or deserialization.

**Comment by grannypron** [comment]
Actually, deserialization and serialization seem to be working find and just using regular strings.  I think the import might be what is getting in the way.

**Comment by grannypron** [comment]
Yes, the object that is passed into ITEM_DATA_TYPE::AddItem() from the DecodeFile() has 0 base classes in it so this is not a problem in the logic of the ITEM_DATA object (yet), but in the Import/export process.  Can't see where it is parsing those lines though.

**Comment by grannypron** [comment]
Got it!  DitemBaseclass() in ItemDB.cpp

**Comment by grannypron** [comment]
Oh there is a line in there that says to remove all the baseclasses for the item if it sees "any":

```
if ((pkt->value=="") || (pkt->value.CompareNoCase("any") == 0)) {
    tempITEM.usableByBaseclass.RemoveAll();
  }
```

Since this code is already in there, it seems like it makes sense to change IsUsableByBaseclass() / IsUsableByClass() to check to see if the item's baseclass collection is empty instead.  Seems like this was the original intention.
