### ISSUE TITLE
Import from FRUA menu item disabled

### ISSUE THREAD

**Issue by cp1103market** [grannypron/uaf#59]
Has this feature been disabled on purpose, because the menu item for 'Import FRUA' is disabled for me.  
Was this feature broken, and if so , are there any plans to fix it?

**Comment by grannypron** [comment]
Yeah as I recall, this was available in a much much earlier version, but then they disabled it at some point.  You can probably confirm over on the message boards with Manikus and/or Paul.

**Comment by cp1103market** [comment]
Will do, thanks!
