### ISSUE TITLE
Increase number of tales available in the Tavern event to 255

### ISSUE THREAD

**Issue by grannypron** [grannypron/uaf#61]
When adding tavern tales in the Tavern event (not the Tavern Tales event), the user is limited to 20 because the spinnner goes back to 1 after 20.  The game engine (UAFWin) supports 255 in GameEvent.cpp, so increase the spinner maximum to 255 as well.  This is related to #60  as a temporary fix.

**Comment by grannypron** [comment]
[DungeonCraft_uaf60.zip](https://github.com/grannypron/uaf/files/10361680/DungeonCraft_uaf60.zip)

Should be a one line change to GameEvent.h to set MAX_TALES = 255.  Debug build attached.

**Comment by grannypron** [comment]
[DungeonCraft_uaf60-release.zip](https://github.com/grannypron/uaf/files/10363134/DungeonCraft_uaf60-release.zip)

**Comment by manikus** [comment]
I did not try adding 255 events...but I did add past 20 and it worked just like it should. Thank you.

**Comment by grannypron** [comment]
Fixed with the comment that was marked as the fix.
