### ISSUE TITLE
Allow ready status of NPC items to be edited in the level editor

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#66]
NPCs created in the editor (please test by creating a  new NPC) do not ready items. NPCs imported who have the items set to ready, do have the item readied when they enter play.
The AI should ready the appropriate items by default, i.e. best weapon, best armor, etc.

**Comment by manikus** [comment]
Here is the design that shows the NPC issue. Use the playfile for play-through. The old NPCs come into game with items readied (the first 2), the new NPC does not. It does ready item in Combat under AI control, but if it had been under Player control, it would not have.
[230303_NPCready_DESIGN.zip](https://github.com/grannypron/uaf/files/10887374/230303_NPCready_DESIGN.zip)

**Comment by grannypron** [comment]
Excellent test case, thanks.  So, in the case of player control, you want the NPC to equip their best items?  Is there any scripting hooks for the case where the NPC is player controlled?   Are we talking about creating one?   Could I suggest that another approach is just to equip the items on the NPC in the design?

**Comment by grannypron** [comment]
The out-of-the-box NPCs have been saved in the default game.dat with their items being readied.  New NPCs will not have the ready status set.  Task is to allow editing of ready status in the editor.

**Comment by grannypron** [comment]
[DungeonCraft_uaf66.zip](https://github.com/grannypron/uaf/files/10915278/DungeonCraft_uaf66.zip)
