### ISSUE TITLE
Grant XP of all items to party during CombatTreasure and Give Treasure events

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#67]
When items are set to give experience points, they do not.

https://forums.goldbox.games/index.php?topic=4357.msg62276#msg62276

**Comment by grannypron** [comment]
Do designers usually couple a Give Experience with Give Treasure to do this?  And are we expecting that same behavior to occur if we are now granting XP with Give Treasure or Combat Treasure?  Like where should the "Your party has gained X experience" message go in the case of a Give Treasure?  Or should there not be one?

**Comment by manikus** [comment]
I don't recall a message appearing when this worked in DC, but I might be wrong.
However this gets resolved, as a designer who doesn't wish to receive any messages saying, "The Party has received 0 XP.

**Comment by grannypron** [comment]
Yes you're right sorry I see that the Gain Experience event allows the message to be blank (presumably not showing any message). 
 
Right now, the only use that I see for the experience value is that it gets calculated is COMBAT_DATA::DetermineVictoryExpPoints(), which I assume is used after a battle.  So, is the task here to grant experience points (invisibly) when the Give Treasure event happens as well?  Or some other place(s) as well?

**Comment by manikus** [comment]
It's been a very long time since I used this feature, but I do know for sure that XP was only given when an event gave the items to the party, not when they traded them amongst themselves, removed from a Vault, or bought in a Shop. So that means it can only be the Give Treasure and Combat Treasure events. I also believe that the XP was given silently.
What I can not recall at all is if the XP was divided evenly amongst the party members, or if it went to the selected party member. Thinking  about how FRUA works, I would wager a guess that it divides the XP amongst the party members.

**Comment by grannypron** [comment]
So this is specifically targeting granting XP on the Give Treasure and Combat Treasure events and we are deciding to assign it silently.  Do we need to socialize that with the forum?  And we would follow the existing logic and divide up amongst party members.

**Comment by manikus** [comment]
right. Give silently with either the Give Treasure or Combat Treasure events, dividing the XP points up evenly by the party.

Those that have commented in the forum are onboard with this.

**Comment by grannypron** [comment]
Just to be clear and specific, the XP will be awarded regardless of whether or not the party actually takes the particular item(s) on the TAKE_TREASURE event/screen.  If that is not the desired behavior, please let me know.

**Comment by grannypron** [comment]
[DungeonCraft_uaf67.zip](https://github.com/grannypron/uaf/files/11008622/DungeonCraft_uaf67.zip)

**Comment by manikus** [comment]
> Just to be clear and specific, the XP will be awarded regardless of whether or not the party actually takes the particular item(s) on the TAKE_TREASURE event/screen. If that is not the desired behavior, please let me know.

I honestly don't know how DnD handles this. It seems like you should get the XP for just finding it - the act of picking something up doesn't seem like that is what generates the XP.
I think it is fine this way.
