### ISSUE TITLE
DungeonCraftEditor_uaf66- importing spells database throws up multiple errors and causes Crash to Desktop

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#68]
When attempting to import the spells.txt file (default one in TemplateDesign.dsn) I get the same error 8 or 9 times (see attached).
If I choose Ignore each time, database does load. If I choose Retry, I get a Crash to Desktop.
![error](https://user-images.githubusercontent.com/19917727/225968537-3f735865-aa5f-4b20-a597-03ec882cfe5e.png)

**Comment by grannypron** [comment]
Line 5293 is a debug assertion that is thrown to catch a special case.  In this case, the code comments say:

    // a spell script was given before the associated spell effect
    ASSERT(FALSE);

**Comment by grannypron** [comment]
I can only find the binary spells.dat in the downloads.  Can you attach the spells.txt that you are using?

**Comment by manikus** [comment]
I am using the default spells database.
https://github.com/manikus/default_databases_for_Dungeon_Craft/blob/main/spells.txt

**Comment by grannypron** [comment]
Here are the specific spells that are being loaded when the assertion is failing:

Remove Curse
Raise Dead
Remove Curse|Wizard
Mass Charm
Remove Curse|Paladin
Heal|MonsterCleric 
Mass Charm|MonsterMage

Looks like for Raise Dead it is happening in Modify as well as the Activate script.  Hope that helps.

**Comment by manikus** [comment]
I will definitely take a look at those spells and see what I can fix.
But, no matter how bad the scripting is, it shouldn't cause the editor to crash, it should just reject the particular record of the database.

**Comment by manikus** [comment]
Okay, double and triple checking here.
The crash is happening with DungeonCraftEditor_uaf66 only (not with DungeonCraftEditor_5_30).
There are no errors in the scripts for Raise Dead. DC does not report any when loading the database. Looking at the spell in the spell editor, when you select the script button, there is no option to check activation or modification scripts. Those can only be examined through the spell effect.
Obviously, these scripts need to be called by a different part of the spell, but not sure how designer would know this.

Not really part of this bug, but maybe we need the editor to spit out an error if someone has scripts to modify the spell effect but there is no spell effect. Though, wih that being said, that part of the spell still works even though the scripts are in the wrong place.

**Comment by manikus** [comment]
Further examination reveals that the problem is the spell effect is missing from Raise Dead. I have re-added it.
This was also the issue for all of the other spells.
After adding back the spell effects, attempting to import, still getting the same error message, with a CtD if I chose retry. If I chose ignore, those spells were not imported.

**Comment by grannypron** [comment]
Asserts get hidden on release build.  The _uaf66 was a quickie Debug build that I did.  That's why you are seeing it in that build and not in the 5.30 release.  In the release version, the spell will probably have some unexpected side effects.

If it is still happening, the line number may have changed.  Can I see another error message screenshot or get the revised spells.txt?

**Comment by manikus** [comment]
It is happening just one time now, still at line 5283. I am using this database attached below
[spells.txt](https://github.com/grannypron/uaf/files/11024202/spells.txt)

**Comment by grannypron** [comment]
The error is in the Activate script of Heal|MonsterCleric

**Comment by manikus** [comment]
At least this error, while with the same script, was something new. It is resolved and I no longer receive an error message upon importing the spells database.

**Comment by grannypron** [comment]
Great!  If you think we should add a message on these assertions, lmk and we can do that, but there are likely many assertions like this spread throughout the editor (and game) so it would be a break from the normal behavior.

**Comment by manikus** [comment]
I think we're fine the way it is.
