### ISSUE TITLE
Sleep spell bug: PCs never wake up

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#70]
When the Sleep spell is cast on a PC, it does not wear off, and the PC remains asleep.
The two Special Abilities associated with this spell are spell_Sleep and IsSleeping.

I've attached a mini-mod that demonstrates this issue. (Need to add Resources directory and the 5.30 engine)
[sleeping_bug_mini-mod.zip](https://github.com/grannypron/uaf/files/11030971/sleeping_bug_mini-mod.zip)

**Comment by manikus** [comment]
It looks like this is happening for more than just one spell, likely for all.
https://forums.goldbox.games/index.php?topic=4361.msg62476#msg62476

**Comment by grannypron** [comment]
Evaluated that this is probably best fixed in the spell databases.  See discussion on the forums.
