### ISSUE TITLE
$CHAR_REMOVESPELL and $CHAR_REMOVEALLSPELLS

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#71]
These functions were the way that a designer (in theory) could remove a memorized spell from a PC.
But, I notice that $CHAR_REMOVESPELL is not available - commented out, and $CHAR_REMOVEALLSPELLS does nothing.

What they are supposed to do:
$CHAR_REMOVESPELL : remove a specific spell from the target, i.e. no longer memorized.
$CHAR_REMOVEALLSPELLS: remove all spells of a given level from the target, i.e. make them no longer memorized.

I see no other functions that will remove a memorized spell from the target, can you verify this? I was looking in GPDLComp.cpp and GPDLExec.cpp where I believe all functions are listed.

**Comment by grannypron** [comment]
As far as I can see, those two macros call RemoveSpellByName and RemoveAllSpellEffectsByLevel, which remove spell effects from a character, not memorized spells.  To me it looks like to remove a memorized spell, one would call DecMemorized() in Char.cpp and I couldn't find any macro that does this.

Given this, not sure what the task is.

**Comment by manikus** [comment]
Hmmm, I thought removing spell effects was done by $REMOVE_SPELL_EFFECT used in conjunction with $RUN_CHAR_SE_SCRIPTS.
Clearing this up for me would be great. :)
 I do not require any action further than that - I will change documentation to mirror what is actually happening.

Regarding removing memorized spells will you confirm that $SetMemorizeCount will still do this (by setting the adjustment to have 0 memorized).

**Comment by manikus** [comment]
Thanks a lot.
