### ISSUE TITLE
Dropping item causes hammer icon to display at that location

### ISSUE THREAD

**Issue by Tzudonym** [grannypron/uaf#76]
Whenever you drop any item in game, the first frame of item_Hammer.png displays at that location in 3D view. Apparently this was some kind of place holder for back when there were intentions to enable players to pick up dropped items, but was never implemented.

Full discussion and further details can be found here:
https://forums.goldbox.games/index.php?topic=4390.0

I'm not sure if there's still an intention to implement that feature, but are we able to remove this for those of us happy enough to work with things as they are?

**Comment by grannypron** [comment]
Shall we a configuration file parameter to turn the function off/on, then?

**Comment by grannypron** [comment]
[DungeonCraft_6ad1def.zip](https://github.com/grannypron/uaf/files/11911218/DungeonCraft_6ad1def.zip)

**Comment by Tzudonym** [comment]
I'm still seeing the icon when I drop stuff.

**Comment by grannypron** [comment]
Are you using the release attached at the link above and not the one attached for #77 ?

**Comment by Tzudonym** [comment]
Yes I am.

**Comment by grannypron** [comment]
Can we get a second person to try it?  I just tried it myself and I don't get the hammer icon anymore.  I go into encamp, view a person, and their inventory and drop an item.  No hammer icon.  Tried it with an older version and I do get the hammer icon.  You want to be running the file called DungeonCraft_6ad1def.exe when you start it in your design.

**Comment by Tzudonym** [comment]
Apologies, rookie mistake, I didn't have one of the exe files in the correct folder.
Works just like you said.
